version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travelconnect-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT:-3002}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:4200,http://frontend:80}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:4200}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-travelconnect_super_secret_refresh_key_2024}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-30d}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      UPLOAD_PATH: ${UPLOAD_PATH:-./uploads}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
      SOCKET_CORS_ORIGIN: ${SOCKET_CORS_ORIGIN:-http://localhost:4200}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-AIzaSyAR6BJ14sWn5T9nn8Hy0C9XyqLUR7vF06k}
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "${BACKEND_PORT:-3002}:3002"
    networks:
      - travelconnect-network

  # Frontend Application
  frontend:
    image: nginx:stable
    container_name: travelconnect-frontend
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    depends_on:
      - backend
    networks:
      - travelconnect-network

volumes:
  backend_uploads:
    driver: local
  frontend_build:
    driver: local

networks:
  travelconnect-network:
    driver: bridge
