version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travelconnect-backend-prod
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3002
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-30d}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}
      SOCKET_CORS_ORIGIN: ${SOCKET_CORS_ORIGIN:-http://localhost}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      UPLOAD_PATH: ${UPLOAD_PATH:-./uploads}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
    ports:
      - "3002:3002"
    volumes:
      - uploads_data:/app/uploads
      - backend_logs:/app/logs
    networks:
      - travelconnect-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend (Angular)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: travelconnect-frontend-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - uploads_data:/usr/share/nginx/html/uploads:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - travelconnect-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Nginx Load Balancer (Optional for high availability)
  nginx-lb:
    image: nginx:alpine
    container_name: travelconnect-nginx-lb
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx-lb.conf:/etc/nginx/nginx.conf:ro
    networks:
      - travelconnect-network
    depends_on:
      - frontend
    profiles:
      - lb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Monitoring with Watchtower (Auto-updates)
  watchtower:
    image: containrrr/watchtower
    container_name: travelconnect-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=true
    profiles:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  uploads_data:
    driver: local
  backend_logs:
    driver: local

networks:
  travelconnect-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
