# TravelConnect Portainer Stack for Git Repository Deployment
# Use this stack when deploying from Git repository in Portainer

version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: travelconnect-backend:latest
    container_name: travelconnect-backend-prod
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3002
      # MongoDB Atlas Connection
      MONGODB_URI: ${MONGODB_URI}
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-30d}
      # Google Maps API
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      # CORS and Frontend
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}
      SOCKET_CORS_ORIGIN: ${SOCKET_CORS_ORIGIN:-http://localhost}
      # File Upload
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
      UPLOAD_PATH: ${UPLOAD_PATH:-./uploads}
      # Rate Limiting
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
    ports:
      - "3002:3002"
    volumes:
      - uploads_data:/app/uploads
      - backend_logs:/app/logs
    networks:
      - travelconnect-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend (Angular with Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: travelconnect-frontend:latest
    container_name: travelconnect-frontend-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - uploads_data:/usr/share/nginx/html/uploads:ro
    networks:
      - travelconnect-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  uploads_data:
    driver: local
  backend_logs:
    driver: local

networks:
  travelconnect-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# ENVIRONMENT VARIABLES TO SET IN PORTAINER:
#
# Required:
# MONGODB_URI=mongodb+srv://lahari:9R8En3qh7Csjd8Ve@travelconnect.jovulzu.mongodb.net/travelconnect?retryWrites=true&w=majority&appName=travelconnect
# JWT_SECRET=travelconnect_super_secret_jwt_key_2024
# JWT_REFRESH_SECRET=travelconnect_super_secret_refresh_key_2024
# GOOGLE_MAPS_API_KEY=AIzaSyAR6BJ14sWn5T9nn8Hy0C9XyqLUR7vF06k
#
# Optional (with defaults):
# JWT_EXPIRES_IN=7d
# JWT_REFRESH_EXPIRES_IN=30d
# FRONTEND_URL=http://your-ec2-public-ip-or-domain
# SOCKET_CORS_ORIGIN=http://your-ec2-public-ip-or-domain
# MAX_FILE_SIZE=10485760
# UPLOAD_PATH=./uploads
# RATE_LIMIT_WINDOW_MS=900000
# RATE_LIMIT_MAX_REQUESTS=100
